### ISSUE TITLE
Document how to have a request on a website recodgnized

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-api#20]
Perhaps for each route we have we could have a "here's how to make this method work"

I got this note at the URSSI workshop:

> I'm trying to figure out how to make CiteAs work on our website (http://einsteintoolkit.org).
>
> I can't figure out what to do based on the instructions on the site, nor is it obvious why it thinks the proper citation is "American Psychological Association, 6th edition." ???
> 
> Anyway, I can't put a CITATION in the root of the website (since that only seems to work for github repo), nor can I put a DOI in the comments on the home page (it doesn't pick that up).
> 
> What should I do?
> 
> I'd like to suggest a CITATION file in the root of the website, similar to what you expect in the repo.
> 
> Thanks.
> 
> --Steve

I think that's also a suggestion of a CITATION file at the root of a website, if a project doesn't use github.

**Comment by jameshowison** [comment]
http://citeas.org/cite/http://einsteintoolkit.org

Says that it "found the citation metadata" but it's not clear what it found?

**Comment by hpiwowar** [comment]
For ticket clarification:  It looks like the project added a DOI to its page source as a comment, and CiteAs is finding it, and displaying the DOI metadata as the correct citation.  So it is all working fine right now.  
To close the issue we should do as the title says -- add documentation so that software devs know what to add to their websites to get CiteAs to pick up their intended citation.

**Comment by hpiwowar** [comment]
More explicit docs added here: http://citeas.org/modify-your-citation
which is linked to from the About page.
