### ISSUE TITLE
If fail, show what was tried and link to new "how to improve" page.

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-api#25]
If we fail to find anything, might we show what was tried (just as on results page, but all shows as unsuccessful), as well as link to http://citeas.org/modify-your-citation to educate improvement.

**Comment by hpiwowar** [comment]
It's a great idea to put in education links there, and I've updated the "file a bug" link to be to the github issues page so people can let us know more directly about bugs.  (Showing what was tried won't always work, because sometimes we throw an error and can't easily get to that spot.)

Now looks like this:
![image](https://user-images.githubusercontent.com/223105/38961995-0fa323d2-4320-11e8-9dc2-17310633c208.png)

Great idea.
