### ISSUE TITLE
CRAN author name not read from DESCRIPTION file

### ISSUE THREAD

**Issue by AlastairKelly** [Impactstory/citeas-api#49]
I see you have struggled with the author names from the DESCRIPTION files already. I'm not sure why this one doesn't work: http://citeas.org/cite/https://cran.r-project.org/web/packages/rowr/index.html Perhaps the file is constructed incorrectly? 

I wasn't sure if you would like this added on to #11 where author names are a secondary concern within a different issue, but please combine if more appropriate.

**Comment by caseydm** [comment]
Hello. The reason that authors are not displayed for that package is because the owner has not formatted the DESCRIPTION file in a way the software can understand it. [This](http://r-pkgs.had.co.nz/description.html) web page shows the recommended way to format authors in a DESCRIPTION file, which is like this:

```
Authors@R: c(person("Matt","Nunes",role=c("aut","cre"),
        email="nunesrpackages@gmail.com"),person("Dennis", "Prangle",
        role="aut",email="d.b.prangle@newcastle.ac.uk"),
	person("Guilhereme", "Rodrigues", role="ctb",
	email="g.rodrigues@unsw.edu.au"))
```

The rowr package you referenced has the author formatted like:
`Author: Craig Varrichio <canthony427@gmail.com>`

Looking at the ABCtools package, for example, it is parsed correctly by CiteAs due to the authors being listed in the proper format:
http://citeas.org/cite/https://cran.r-project.org/web/packages/abctools/

That being said, I scrolled through several packages and do see that some others are using the plain format. So I will attempt to support it shortly.

**Comment by caseydm** [comment]
Hello again! I just made an update so almost every author format is pulled from the DESCRIPTION file now. The example you mentioned is working. Please take a look.
