### ISSUE TITLE
Occasional failure in building citation

### ISSUE THREAD

**Issue by caifand** [Impactstory/citeas-api#52]
Hi, I am working with @jameshowison and we have been showing and discussing CiteAs to other researchers. Sometimes users put in an appropriate handle in the search bar but CiteAs prompts them "Sorry!" and "We weren't able to figure out a citation for this research product." This even happens to the examples provided on the homepage (e.g., yt project, etc.) sometimes. i.e., this failure in building citation is not due to the real absence of information but is temporary.

Usually I found if I change to another browser the same search can work again. But sometimes it totally cannot work. I asked someone to try CiteAs in 3 different browsers this morning but it just cannot return any successfully built citation.

Do you have any thought on what the possible reason might be? e.g., should we suggest others to clean up their cookies first when then encounter such failure with CiteAs?

Thanks for your consideration.

**Comment by caseydm** [comment]
Hello. This is interesting. I always use Chrome and have had a lot of success lately testing random URLs from GitHub, web pages, DOIs, etc. I will check the server logs to see if some kind of error is occurring on the front end of the web app.

Do you have an example of the resource that was not working well this morning? One thing that I will do is test it in the API which powers the web site. This is accessed via 
https://api.citeas.org/product/{resource}. If it works there but not on the web page then I know the issue is maybe browser related.

Definitely want to get to the bottom of this!

**Comment by caseydm** [comment]
Hello again. I looked through the logs and cannot find any recent errors. There were some bugs a few weeks ago that were resolved. Please let me know if you are still having any issues.
